version: '3'

services:
  sleek-airflow:
    image: sleekdataairflow:latest
    ports:
      - "8080:8080"
    volumes:
      - ./airflow:/opt/airflow
    command: airflow standalone
  sleek-smtp:
    image: bytemark/smtp
    restart: always
